# Generated by Django 4.2.3 on 2023-08-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='periodo',
            new_name='periodocurso',
        ),
    ]
